### PR TITLE
Remove mmeshFromSource test.

### PR DESCRIPTION
**Pull request by samuelburbulla**
I observed that this test actually never really worked.
As I don't have any good idea to fix it, I propose to simply remove this case.

In previous runs an older version of pip used the package on PyPI as fallback, therefore it succeeded.
Building MMesh from source is an issue as the packaging script does not do the right thing for the differing version number in MMesh. It is working with the customised setup.py, but not for the generated one. Maybe one could generalise the packaging script, but I have no time to look into this right now.

### CODE REVIEW

**Comment by adedner** [comment]
@samuelburbulla I tried your fix in `dune-common` and that leads to another error (see
https://github.com/adedner/dune-testpypi/actions/runs/2201220527).

I setup a branch `bugfix/testmmsh` where I clone into the correct mmsh branch (I think). I then ran the tests action using the `dune-common` branch `feature/generalize-packaging-script`. 

Could you have a look?

**Comment by samuelburbulla** [comment]
The issue is that we are now mixing mmesh master with the dune-common package on PyPI.

The newly generated pyproject.toml (including the # comment block) is not handled correctly in dune-common 2.8.
Further, the packagemetadata in setup.py will fail because it will not use the new generation of this object.

As soon as we update dune-common this test should work.
In the meantime, we will only be able to test dune-mmesh with the source modules.

**Comment by adedner** [comment]
Perhaps I misunderstand something. In the 'build' stage we have
```
2022-04-21T10:24:51.4276321Z Downloading dune-common into /home/runner/work/dune-testpypi/dune-testpypi
2022-04-21T10:24:53.3033182Z cloned dune-common feature/generalize-packaging-script
```
so we are not using master of dune-common but your branch.

For the actual test we have
```
2022-04-21T10:38:29.2625372Z cloning dune-mmesh with branch feature/generalize-packaging-script
2022-04-21T10:38:29.2626411Z cloning called for module:dune-mmesh path:https://gitlab.dune-project.org/samuel.burbulla/dune-mmesh.git version:feature/use-packaging-script tag:feature/use-packaging-script into /home/runner/work/dune-testpypi/dune-testpypi/test
2022-04-21T10:38:29.4137569Z Try cloning from https://gitlab.dune-project.org/samuel.burbulla/dune-mmesh.git branch feature/use-packaging-script
2022-04-21T10:38:29.4158725Z Cloning into 'dune-mmesh'...
2022-04-21T10:38:33.4799510Z Filtering content:  10% (2/20)

2022-04-21T10:38:34.0206495Z Filtering content:  95% (19/20), 1011.95 KiB | 1.34 MiB/s
2022-04-21T10:38:34.0208685Z Filtering content: 100% (20/20), 1011.95 KiB | 1.34 MiB/s
2022-04-21T10:38:34.0209121Z Filtering content: 100% (20/20), 1.72 MiB | 756.00 KiB/s, done.
2022-04-21T10:38:34.0467719Z commit a5e749c97dde07cf6512af61410fcfad9bb0dfde
2022-04-21T10:38:34.0468793Z Author: Samuel Burbulla <samuel.burbulla@mathematik.uni-stuttgart.de>
2022-04-21T10:38:34.0469504Z Date:   Tue Apr 12 20:47:53 2022 +0200
2022-04-21T10:38:34.0469782Z 
2022-04-21T10:38:34.0470468Z     Specify package version requirements in dune.module.
2022-04-21T10:38:34.0497694Z Use dev versioning
```
which is the branch were you added the change. The error is now also different, i.e., not that it  is not finding the right version but

```
2022-04-21T10:39:30.7876375Z         File "setup.py", line 13, in <module>
2022-04-21T10:39:30.7876687Z           setup(**metaData('1.4.0.dev20220421')[1])
2022-04-21T10:39:30.7877743Z         File "/tmp/pip-build-env-k4oayrq8/overlay/lib/python3.9/site-packages/dune/packagemetadata.py", line 326, in metaData
2022-04-21T10:39:30.7878192Z           line = line.split('=',maxsplit=1)[1].strip()
2022-04-21T10:39:30.7878431Z       IndexError: list index out of range
2022-04-21T10:39:30.7878648Z       [end of output]
```

So there is now a bug in packaging?

**Comment by samuelburbulla** [comment]
This is because of the build isolation of pip.

````
File "/tmp/pip-build-env-k4oayrq8/overlay/lib/python3.9/site-packages/dune/packagemetadata.py", line 326, in metaData
  line = line.split('=',maxsplit=1)[1].strip()
IndexError: list index out of range
````
says it happens in line 326, but this is different on our requested branch, it was there in 2.8.0.

I tried to disable the build isolation locally, but then dune-common has not been found.

**Comment by adedner** [comment]
I still don't understand - why is it not using the dev version. Is that because dune-mmsh has 1.4 has base version and the dev package of dune-common is 2.9? But then merging the changes into dune-common wouldn't make any difference, right? After the build stage we simple have the dev package and those are the same independent of the branch used in dune-common in the build step?

**Comment by samuelburbulla** [comment]
Okay, I see a point, it should take the package from outside if the version number is sufficient, right?
However, in this specific case, as I now specify the version of dune-grid<=2.8.0.post2 in Python-Requires and pass this to the pyproject.toml, we get the mismatch with to the 2.9.dev version. I simply do not have 2.9dev for dune-common any more, but implicitly <=2.8.0.post2.
And this is what I more or less want for packaging, taking the specified version.
This test case is a little weird, because we mix package with git master.

Merging the changes in dune-common would only apply if we upload a new package to pypi and request this version in dune-mmesh.

I do not fully understand your last question. As mentioned above, I think the built package is used if the versions match.

**Comment by adedner** [comment]
> This test case is a little weird, because we mix package with git master.
We are mixing packages generated from the git sources with a new git source. Perhaps that is not a good test as you suggest. Perhaps dune-mmsh master just has to work with (a) the sources of the other modules and (b) with the latest dev package on pypi and that should be tested here.

**Comment by samuelburbulla** [comment]
Actually, (a) is tested in dune-mmesh itself already.
We run the tests (including python tests) on the current master of all core modules at every push.

The pypi packages are also tested every day, but of course, only the already published one.

The piece that is missing is the testing of the package's source distribution of the master, before we publish it on pypi.

One issue I realised is that fixing the version number of dune-grid<=2.8.0.post2 is wrong, as we require a more recent dune-common with the recent changes in the package metadata. I will try again with another version specifier.

**Comment by samuelburbulla** [comment]
Okay, I fixed it.

**Pull request closed without merging**
